/**
 * Deploy AidVocate contracts to local Hardhat network or Polygon Amoy testnet.
 *
 * Usage:
 *   npx hardhat run scripts/deploy.js                          # local
 *   npx hardhat run scripts/deploy.js --network amoy           # testnet
 *
 * Prerequisites:
 *   - Groth16Verifier.sol must exist in contracts/ (run circuits/scripts/export-verifier.sh first)
 *   - For Amoy: set DEPLOYER_PRIVATE_KEY and optionally AMOY_RPC_URL in environment
 */
import hre from "hardhat";

async function main() {
  const network = await hre.network.connect();
  const { ethers } = network;

  console.log("Deploying contracts...");

  // Deploy Groth16Verifier (auto-generated by snarkjs export)
  let verifierAddress;
  try {
    const Verifier = await ethers.getContractFactory("Groth16Verifier");
    const verifier = await Verifier.deploy();
    verifierAddress = await verifier.getAddress();
    console.log("Groth16Verifier deployed to:", verifierAddress);
  } catch (err) {
    console.warn("Groth16Verifier not found — using MockVerifier instead.");
    console.warn("Run packages/circuits/scripts/export-verifier.sh to generate the real verifier.");
    const MockVerifier = await ethers.getContractFactory("MockVerifier");
    const mock = await MockVerifier.deploy();
    verifierAddress = await mock.getAddress();
    console.log("MockVerifier deployed to:", verifierAddress);
  }

  // Deploy AidVocate with verifier address
  const AidVocate = await ethers.getContractFactory("AidVocate");
  const aidvocate = await AidVocate.deploy(verifierAddress);
  const aidvocateAddress = await aidvocate.getAddress();
  console.log("AidVocate deployed to:", aidvocateAddress);

  console.log("\nDeployment complete. Set these in your .env:");
  console.log(`  CONTRACT_ADDRESS=${aidvocateAddress}`);
  console.log(`  VERIFIER_ADDRESS=${verifierAddress}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
