/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AidVocateInterface extends Interface {
    getFunction(nameOrSignature: "batchCount" | "getMerkleRoot" | "merkleRoots" | "owner" | "renounceOwnership" | "storeMerkleRoot" | "transferOwnership" | "verifier" | "verifyDonation"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DonationVerified" | "MerkleRootStored" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'batchCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMerkleRoot', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'merkleRoots', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'storeMerkleRoot', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifier', values?: undefined): string;
encodeFunctionData(functionFragment: 'verifyDonation', values: [[BigNumberish, BigNumberish], [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], [BigNumberish, BigNumberish], [BigNumberish], BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'batchCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMerkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'merkleRoots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'storeMerkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyDonation', data: BytesLike): Result;
  }

  
    export namespace DonationVerifiedEvent {
      export type InputTuple = [batchId: BigNumberish, valid: boolean, timestamp: BigNumberish];
      export type OutputTuple = [batchId: bigint, valid: boolean, timestamp: bigint];
      export interface OutputObject {batchId: bigint, valid: boolean, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MerkleRootStoredEvent {
      export type InputTuple = [batchId: BigNumberish, root: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [batchId: bigint, root: string, timestamp: bigint];
      export interface OutputObject {batchId: bigint, root: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AidVocate extends BaseContract {
    
    connect(runner?: ContractRunner | null): AidVocate;
    waitForDeployment(): Promise<this>;

    interface: AidVocateInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    batchCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getMerkleRoot: TypedContractMethod<
      [_batchId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    merkleRoots: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    storeMerkleRoot: TypedContractMethod<
      [_root: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    verifyDonation: TypedContractMethod<
      [_pA: [BigNumberish, BigNumberish], _pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], _pC: [BigNumberish, BigNumberish], _pubSignals: [BigNumberish], _batchId: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'batchCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMerkleRoot'): TypedContractMethod<
      [_batchId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'merkleRoots'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'storeMerkleRoot'): TypedContractMethod<
      [_root: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'verifyDonation'): TypedContractMethod<
      [_pA: [BigNumberish, BigNumberish], _pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], _pC: [BigNumberish, BigNumberish], _pubSignals: [BigNumberish], _batchId: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;

    getEvent(key: 'DonationVerified'): TypedContractEvent<DonationVerifiedEvent.InputTuple, DonationVerifiedEvent.OutputTuple, DonationVerifiedEvent.OutputObject>;
getEvent(key: 'MerkleRootStored'): TypedContractEvent<MerkleRootStoredEvent.InputTuple, MerkleRootStoredEvent.OutputTuple, MerkleRootStoredEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'DonationVerified(uint256,bool,uint256)': TypedContractEvent<DonationVerifiedEvent.InputTuple, DonationVerifiedEvent.OutputTuple, DonationVerifiedEvent.OutputObject>;
      DonationVerified: TypedContractEvent<DonationVerifiedEvent.InputTuple, DonationVerifiedEvent.OutputTuple, DonationVerifiedEvent.OutputObject>;
    

      'MerkleRootStored(uint256,bytes32,uint256)': TypedContractEvent<MerkleRootStoredEvent.InputTuple, MerkleRootStoredEvent.OutputTuple, MerkleRootStoredEvent.OutputObject>;
      MerkleRootStored: TypedContractEvent<MerkleRootStoredEvent.InputTuple, MerkleRootStoredEvent.OutputTuple, MerkleRootStoredEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }