/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aidVocateSol from './AidVocate.sol/index.js';
export type { aidVocateSol };
import type * as mocks from './mocks/index.js';
export type { mocks };
export type { Groth16Verifier } from './Groth16Verifier.js';
export * as factories from './factories/index.js';
export type { AidVocate } from './AidVocate.sol/AidVocate.js';
export { AidVocate__factory } from './factories/AidVocate.sol/AidVocate__factory.js';
export type { IVerifier } from './AidVocate.sol/IVerifier.js';
export { IVerifier__factory } from './factories/AidVocate.sol/IVerifier__factory.js';
export { Groth16Verifier__factory } from './factories/Groth16Verifier__factory.js';
export type { MockVerifier } from './mocks/MockVerifier.js';
export { MockVerifier__factory } from './factories/mocks/MockVerifier__factory.js';