/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyDonationRouteImport } from './routes/verify-donation'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReceiptRouteImport } from './routes/receipt'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CharitiesRouteImport } from './routes/charities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as CharityIdRouteImport } from './routes/charity.$id'

const VerifyDonationRoute = VerifyDonationRouteImport.update({
  id: '/verify-donation',
  path: '/verify-donation',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptRoute = ReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CharitiesRoute = CharitiesRouteImport.update({
  id: '/charities',
  path: '/charities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CharityIdRoute = CharityIdRouteImport.update({
  id: '/charity/$id',
  path: '/charity/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charities': typeof CharitiesRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/login': typeof LoginRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/receipt': typeof ReceiptRoute
  '/register': typeof RegisterRoute
  '/verify-donation': typeof VerifyDonationRoute
  '/charity/$id': typeof CharityIdRoute
  '/event/$id': typeof EventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charities': typeof CharitiesRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/login': typeof LoginRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/receipt': typeof ReceiptRoute
  '/register': typeof RegisterRoute
  '/verify-donation': typeof VerifyDonationRoute
  '/charity/$id': typeof CharityIdRoute
  '/event/$id': typeof EventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charities': typeof CharitiesRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/login': typeof LoginRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/receipt': typeof ReceiptRoute
  '/register': typeof RegisterRoute
  '/verify-donation': typeof VerifyDonationRoute
  '/charity/$id': typeof CharityIdRoute
  '/event/$id': typeof EventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/charities'
    | '/dashboard'
    | '/donate'
    | '/donations'
    | '/events'
    | '/leaderboards'
    | '/login'
    | '/payment-success'
    | '/receipt'
    | '/register'
    | '/verify-donation'
    | '/charity/$id'
    | '/event/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charities'
    | '/dashboard'
    | '/donate'
    | '/donations'
    | '/events'
    | '/leaderboards'
    | '/login'
    | '/payment-success'
    | '/receipt'
    | '/register'
    | '/verify-donation'
    | '/charity/$id'
    | '/event/$id'
  id:
    | '__root__'
    | '/'
    | '/charities'
    | '/dashboard'
    | '/donate'
    | '/donations'
    | '/events'
    | '/leaderboards'
    | '/login'
    | '/payment-success'
    | '/receipt'
    | '/register'
    | '/verify-donation'
    | '/charity/$id'
    | '/event/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharitiesRoute: typeof CharitiesRoute
  DashboardRoute: typeof DashboardRoute
  DonateRoute: typeof DonateRoute
  DonationsRoute: typeof DonationsRoute
  EventsRoute: typeof EventsRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  LoginRoute: typeof LoginRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ReceiptRoute: typeof ReceiptRoute
  RegisterRoute: typeof RegisterRoute
  VerifyDonationRoute: typeof VerifyDonationRoute
  CharityIdRoute: typeof CharityIdRoute
  EventIdRoute: typeof EventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-donation': {
      id: '/verify-donation'
      path: '/verify-donation'
      fullPath: '/verify-donation'
      preLoaderRoute: typeof VerifyDonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt': {
      id: '/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof ReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charities': {
      id: '/charities'
      path: '/charities'
      fullPath: '/charities'
      preLoaderRoute: typeof CharitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charity/$id': {
      id: '/charity/$id'
      path: '/charity/$id'
      fullPath: '/charity/$id'
      preLoaderRoute: typeof CharityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharitiesRoute: CharitiesRoute,
  DashboardRoute: DashboardRoute,
  DonateRoute: DonateRoute,
  DonationsRoute: DonationsRoute,
  EventsRoute: EventsRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  LoginRoute: LoginRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ReceiptRoute: ReceiptRoute,
  RegisterRoute: RegisterRoute,
  VerifyDonationRoute: VerifyDonationRoute,
  CharityIdRoute: CharityIdRoute,
  EventIdRoute: EventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
