/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockVerifier, MockVerifierInterface } from "../../mocks/MockVerifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256[2]",
        "name": "",
        "type": "uint256[2]"
      },
      {
        "internalType": "uint256[2][2]",
        "name": "",
        "type": "uint256[2][2]"
      },
      {
        "internalType": "uint256[2]",
        "name": "",
        "type": "uint256[2]"
      },
      {
        "internalType": "uint256[1]",
        "name": "",
        "type": "uint256[1]"
      }
    ],
    "name": "verifyProof",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b5060f88061001c5f395ff3fe6080604052348015600e575f80fd5b50600436106026575f3560e01c806343753b4d14602a575b5f80fd5b603f60353660046068565b6001949350505050565b604051901515815260200160405180910390f35b80604081018310156062575f80fd5b92915050565b5f805f80610120808688031215607c575f80fd5b608487876053565b945060c08601878111156095575f80fd5b60408701945060a388826053565b93505086818701111560b3575f80fd5b5092959194509261010001915056fea264697066735822122052a8275ebccb1d46167cd01f793dd7595bea4e23397136bcc12a3cf3ffd23c1b64736f6c63430008140033";

  
      type MockVerifierConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockVerifierConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockVerifier__factory extends ContractFactory {
    
      constructor(...args: MockVerifierConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockVerifier__factory {
      return super.connect(runner) as MockVerifier__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockVerifierInterface {
      return new Interface(_abi) as MockVerifierInterface;
    }
    
    override attach(address: string | Addressable): MockVerifier {
      return super.attach(address) as MockVerifier;
    }
  static connect(address: string, runner?: ContractRunner | null): MockVerifier {
      return new Contract(address, _abi, runner) as unknown as MockVerifier;
    }
  }

  
  