/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as aidVocateSol from './AidVocate.sol/index.js';
export * as mocks from './mocks/index.js';
export { Groth16Verifier__factory } from './Groth16Verifier__factory.js';