/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AidVocate__factory } from './AidVocate__factory.js';
export { IVerifier__factory } from './IVerifier__factory.js';